[workspace]
authors = ["Claudius Kienle <claudius.kienle@tu-darmstadt.de>"]
channels = ["conda-forge"]
name = "pddl-utils"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
bison = ">=3.8.2,<4"
flex = ">=2.6.4,<3"

[pypi-dependencies]
pddl-utils ={ path = ".", editable = true, extras = ["test", "docker"]}
